import assert from "node:assert/strict";
import test from "node:test";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promoteMilimRelease, PromotionError } from "../scripts/promote-milim-release.mjs";

const root=await mkdtemp(path.join(os.tmpdir(),"milim-promotion-test-"));
const hash = value => ({bytes:Buffer.byteLength(value),sha256:createHash("sha256").update(value).digest("hex")});
async function fixture(name="release") { const source=path.join(root,`${name}-${Math.random().toString(16).slice(2)}`), web=path.join(root,`web-${Math.random().toString(16).slice(2)}`); await mkdir(path.join(source,"player"),{recursive:true}); await mkdir(path.join(source,"previews"),{recursive:true}); const payload={"./player/index.js":"export const mountMilim = async () => ({});\n","./previews/desktop.webp":"d","./previews/tablet.webp":"t","./previews/mobile.webp":"m","./previews/reduced.webp":"r"}; for(const [file,contents] of Object.entries(payload)) await writeFile(path.join(source,file.slice(2)),contents); const files=Object.entries(payload).map(([file,contents])=>({path:file,...hash(contents)})); const manifest={format:"milim-release",formatVersion:1,release:"milim-web-0.1.0",compatibility:{major:1},player:{version:"0.1.0",entry:"./player/index.js"},model:{id:"milim-v1",version:"1.0.0",url:"./player/index.js"},scenes:[{id:"cyber-slime-lab-v1",version:"1.0.0",url:"./player/index.js"},{id:"slime-reactor-halo-v1",version:"1.0.0",url:"./player/index.js"},{id:"dragon-signal-observatory-v1",version:"1.0.0",url:"./player/index.js"}],defaults:{hair:"classic-long-pink",outfit:"dragonoid-hoodie-v1",pose:"confident-neutral-v1",expression:"neutral",scene:"cyber-slime-lab-v1"},fallbacks:{desktop:"./previews/desktop.webp",tablet:"./previews/tablet.webp",mobile:"./previews/mobile.webp",reducedMotion:"./previews/reduced.webp"},files,source:{repository:"gaia-research/milim",commit:"abcdef1",releasedAt:"2026-07-16T00:00:00.000Z"}}; await writeFile(path.join(source,"release.json"),JSON.stringify(manifest)); return {source,web}; }
test("promotes one verified immutable release and pins it",async()=>{const {source,web}=await fixture();const result=await promoteMilimRelease({source,release:"milim-web-0.1.0",sourceCommit:"abcdef1",websiteRoot:web});assert.equal(JSON.parse(await readFile(result.currentPath)).release,"milim-web-0.1.0");assert.equal(JSON.parse(await readFile(result.recordPath)).source.commit,"abcdef1");await assert.rejects(()=>promoteMilimRelease({source,release:"milim-web-0.1.0",sourceCommit:"abcdef1",websiteRoot:web}),PromotionError);});
test("refuses a mismatched checksum or commit",async()=>{const {source,web}=await fixture();await writeFile(path.join(source,"player/index.js"),"tampered");await assert.rejects(()=>promoteMilimRelease({source,release:"milim-web-0.1.0",sourceCommit:"abcdef1",websiteRoot:web}),PromotionError);const other=await fixture();await assert.rejects(()=>promoteMilimRelease({source:other.source,release:"milim-web-0.1.0",sourceCommit:"deadbee",websiteRoot:other.web}),PromotionError);});
