#!/usr/bin/env node
/*
 * Promote Milim's Rive build into the site.
 *
 *   node scripts/milim/sync-rive.mjs --riv <path/to/milim.riv> --poster <path/to/poster.png>
 *
 * Copies the .riv and a WebP poster (the static / reduced-motion / fallback
 * frame, rendered from the same rig) under content-hashed names, self-hosts the
 * pinned Rive WebGL2 wasm, and rewrites lib/milim-rive/asset.ts.
 * Source of truth for the character: gaia-research/milim, rive/milim.
 */
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const arg = (k) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : undefined; };
const riv = arg("--riv"), poster = arg("--poster"), sourceCommit = arg("--source-commit") ?? "unknown";
if (!riv || !poster) { console.error("usage: --riv <file> --poster <file> [--source-commit <sha>]"); process.exit(2); }

const sha = (buf) => createHash("sha256").update(buf).digest("hex");
const outDir = join(root, "public/milim");
mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) if (/^milim-[0-9a-f]{10}\.(riv|webp)$/.test(f)) rmSync(join(outDir, f));

const rivBuf = readFileSync(riv);
const rivName = `milim-${sha(rivBuf).slice(0, 10)}.riv`;
writeFileSync(join(outDir, rivName), rivBuf);

const posterBuf = await sharp(poster).webp({ quality: 88, alphaQuality: 100, effort: 6 }).toBuffer();
const posterName = `milim-${sha(posterBuf).slice(0, 10)}.webp`;
writeFileSync(join(outDir, posterName), posterBuf);
const meta = await sharp(posterBuf).metadata();

const pkg = JSON.parse(readFileSync(join(root, "node_modules/@rive-app/webgl2/package.json"), "utf8"));
const wasmName = `rive-webgl2-${pkg.version}.wasm`;
const wasmDir = join(root, "public/rive");
mkdirSync(wasmDir, { recursive: true });
for (const f of readdirSync(wasmDir)) if (f.endsWith(".wasm") && f !== wasmName) rmSync(join(wasmDir, f));
copyFileSync(join(root, "node_modules/@rive-app/webgl2/rive.wasm"), join(wasmDir, wasmName));

writeFileSync(join(root, "lib/milim-rive/asset.ts"), `// Generated by scripts/milim/sync-rive.mjs — do not edit by hand.
export const MILIM_RIVE = {
  src: "/milim/${rivName}",
  riv: { sha256: "${sha(rivBuf)}", bytes: ${rivBuf.length} },
  poster: { src: "/milim/${posterName}", width: ${meta.width}, height: ${meta.height} },
  wasm: "/rive/${wasmName}",
  runtime: "@rive-app/webgl2@${pkg.version}",
  source: { repo: "gaia-research/milim", path: "rive/milim", commit: "${sourceCommit}" },
} as const;
`);
console.log(`riv ${rivName} (${rivBuf.length} B), poster ${posterName} ${meta.width}x${meta.height} (${posterBuf.length} B), wasm ${wasmName}`);
