// Context Diet — SKILL.md export.
//
// Turns a measurement + projection into a GAIA-compatible SKILL.md skeleton, per
// templates/skill-repo/SKILL.template.md. Pure string builder: no network, no
// storage. Only section TITLES and aggregate numbers are emitted — never the
// pasted body text — so the export cannot leak prompt content.

import type { Measured, ReductionBand } from "./types";

export interface SkillMdOpts {
  /** kebab-case skill name; defaults to "context-diet-export". */
  skillName?: string;
  /** one-line tagline under the H1. */
  tagline?: string;
}

const KEBAB = /[^a-z0-9]+/g;

function toKebab(raw: string): string {
  return raw.toLowerCase().replace(KEBAB, "-").replace(/^-+|-+$/g, "") || "context-diet-export";
}

function fmt(n: number): string {
  return n.toLocaleString("en-US");
}

/** Build a GAIA-compatible SKILL.md skeleton from a measured context file. */
export function buildSkillMd(m: Measured, band: ReductionBand, opts: SkillMdOpts = {}): string {
  const name = toKebab(opts.skillName ?? "context-diet-export");
  const tagline =
    opts.tagline ?? "A context diet proposal — retained constraints, measured, and cited.";

  const status = m.overLimit ? `over budget by ${fmt(m.overBy)} chars` : `within budget`;
  const topTargets = m.ranked
    .filter((s) => s.title !== "(preamble)")
    .slice(0, 10)
    .map((s) => `- ${s.title} — ${fmt(s.chars)} chars (~${fmt(s.approxTokens)} tok)`)
    .join("\n");

  // Emit a literal template block for "Reading the output" so the export shows a
  // realistic sample without echoing any pasted text.
  const sampleOutput = [
    `Total: ${fmt(m.totalChars)} chars (~${fmt(m.approxTokens)} tok)  ·  limit ${fmt(m.limit)}  ·  ${status}`,
    m.overLimit
      ? `Over by ${fmt(m.overBy)} chars — must shed at least this to fit.`
      : `Headroom: ${fmt(m.headroom)} chars.`,
    `Sections: ${m.sectionCount}`,
    `Projected reduction: ${band.lowPct}%–${band.highPct}% (target ${band.targetPct}% via ${band.targetTitle}).`,
  ].join("\n");

  return `---
name: ${name}
description: >-
  A Context Diet proposal generated by the Gaia Research lab. Measures an agent
  context file and proposes a reduction while preserving load-bearing rules.
  Triggers: "context diet", ${name}.
version: 1.0.0
---

# ${name} — Context Diet Export

> ${tagline}

## Install

This is a proposal export from the Context Diet lab, not an installable script.
Review it, apply the retained constraints, and cite the evidence below.

## When to use

- An agent context file (CLAUDE.md, .cursorrules, AGENTS.md, a system prompt) is bloated or over its token budget.
- You need to shed tokens without dropping load-bearing instructions.
- You want an auditable before/after with a projected reduction band.

## How it works

1. Measure — split the file on \`##\` headings and count chars/approx tokens per section.
2. Rank — order sections by size to surface the compaction targets below.
3. Project — estimate a reduction band from the four Lab 001 strategies.
4. Export — emit this proposal; the diet remains proposed until its evidence is reviewed.

## Run it

\`\`\`bash
# Reproduce the measurement locally
python3 context_diet.py <your-context-file>.md --json
\`\`\`

## Reading the output

\`\`\`
${sampleOutput}
\`\`\`

### Largest sections (compaction targets)

${topTargets || "- (no sections detected)"}

## Notes

- Projected reduction: ${band.lowPct}%–${band.highPct}%, target ${band.targetPct}% (${band.targetTitle}).
- Evidence: Context Diet — Lab 001 (winner "${band.targetKey}", 41.6% at 100% faithfulness).
- Status: proposed — verify faithfulness before adopting.
- Repo: https://github.com/gaia-research/gaia-research
`;
}
