// Generated by scripts/milim/sync-rive.mjs — do not edit by hand.
export const MILIM_RIVE = {
  src: "/milim/milim-9ed1b78225.riv",
  riv: { sha256: "9ed1b7822518ce2caad7427e88e470aaec63001be251b0bd228b23b280045fe6", bytes: 424536 },
  poster: { src: "/milim/milim-8870ddc9a1.webp", width: 800, height: 1600 },
  wasm: "/rive/rive-webgl2-2.43.1.wasm",
  runtime: "@rive-app/webgl2@2.43.1",
  source: { repo: "gaia-research/milim", path: "rive/milim", commit: "a52b55b" },
} as const;
