// Generated by scripts/milim/sync-rive.mjs — do not edit by hand.
export const MILIM_RIVE = {
  src: "/milim/milim-5aea2675a1.riv",
  riv: { sha256: "5aea2675a11985a8edd16cc0b370f72940392c07b302cac80b58f46f181f8c29", bytes: 689397 },
  poster: { src: "/milim/milim-c7d02c8547.webp", width: 800, height: 1600 },
  wasm: "/rive/rive-webgl2-2.43.1.wasm",
  runtime: "@rive-app/webgl2@2.43.1",
  source: { repo: "gaia-research/milim", path: "rive/milim", commit: "793eaae" },
} as const;
