import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
export type Attempt={schema:"hh-r2-attempt/v1";attemptId:string;taskId:string;loadoutId:string;repeatIndex:number;attemptIndex:number;startedAt:string;finishedAt:string;status:"valid"|"invalid";invalidReason:string|null;artifactSha256:string;ledgerRecordSha256:string|null};
const reasons=new Set(["harness-crash","provider-outage","rate-limit","sandbox-setup","capture-corrupt","endpoint-infrastructure","protocol-deviation"]);
export function validateAttempt(a:any):asserts a is Attempt{if(!a||a.schema!=="hh-r2-attempt/v1")throw new Error("bad attempt schema");for(const k of ["attemptId","taskId","loadoutId","startedAt","finishedAt","artifactSha256"])if(typeof a[k]!=="string"||!a[k])throw new Error(`missing attempt.${k}`);if(!Number.isInteger(a.repeatIndex)||a.repeatIndex<0||!Number.isInteger(a.attemptIndex)||a.attemptIndex<0)throw new Error("bad attempt index");if(!/^[a-f0-9]{64}$/.test(a.artifactSha256))throw new Error("bad artifact hash");if(a.status==="valid"&&(a.invalidReason!==null||!/^[a-f0-9]{64}$/.test(a.ledgerRecordSha256)))throw new Error("valid attempt must reference ledger");if(a.status==="invalid"&&(!reasons.has(a.invalidReason)||a.ledgerRecordSha256!==null))throw new Error("invalid attempt must have reason and no ledger reference");if(!["valid","invalid"].includes(a.status))throw new Error("bad status");}
export function appendShard(path:string,a:Attempt){validateAttempt(a);appendFileSync(path,JSON.stringify(a)+"\n",{flag:"a"});}
export function readAttempts(paths:string[]){return paths.flatMap(p=>existsSync(p)?readFileSync(p,"utf8").split("\n").filter(Boolean).map((line,i)=>{try{const x=JSON.parse(line);validateAttempt(x);return x}catch(e){throw new Error(`${p}:${i+1}: ${(e as Error).message}`)}}):[]);}
export function detectCells(attempts:Attempt[],expected:{taskId:string;loadoutId:string;repeatIndex:number}[]){const key=(x:any)=>`${x.taskId}\u0000${x.loadoutId}\u0000${x.repeatIndex}`,seen=new Set<string>(),duplicates:string[]=[];for(const a of attempts){const k=key(a);if(seen.has(k))duplicates.push(k);seen.add(k)}const es=new Set(expected.map(key));return{duplicates,incomplete:[...es].filter(k=>!seen.has(k)),unexpected:[...seen].filter(k=>!es.has(k)),complete:duplicates.length===0&&es.size===seen.size&&[...es].every(k=>seen.has(k))};}
/** Pending assignments contain hashes only; treatment identity is never written. */
export function blindAssignments(attempts:Attempt[],rubricVersion:string){return attempts.filter(a=>a.status==="valid").map((a,i)=>{const b=attempts.find(x=>x.taskId===a.taskId&&x.status==="valid"&&x.artifactSha256!==a.artifactSha256);if(!b)return null;const [x,y]=[a.artifactSha256,b.artifactSha256].sort();return{assignmentId:createHash("sha256").update(`${a.taskId}:${x}:${y}:${i}`).digest("hex"),taskId:a.taskId,rubricVersion,candidateAArtifactSha256:x,candidateBArtifactSha256:y,status:"pending"};}).filter(Boolean);}
