import { describe, expect, it } from "vitest";
import { enumerateCells } from "./r2-execution";
import { appendShard, blindAssignments, detectCells, validateAttempt } from "./r2-collection";
import { validateJudgeAssignment } from "./r2-contract";
import { analyse } from "./r2-analysis";
import { validateClaims } from "./r2-gates";
const matrix={tasks:[{taskId:"t1",taskPrompt:"x",loadouts:[{id:"placebo",arm:"placebo",rung:"zero",skills:[]},{id:"heaven-low",arm:"heaven",rung:"low",skills:["s1"]}]}]};
const attempt=(repeatIndex:number, hash:string)=>({schema:"hh-r2-attempt/v1",attemptId:`a${repeatIndex}`,taskId:"t1",loadoutId:"placebo",repeatIndex,attemptIndex:0,startedAt:"2026-01-01T00:00:00Z",finishedAt:"2026-01-01T00:00:01Z",status:"valid",invalidReason:null,artifactSha256:hash,ledgerRecordSha256:"a".repeat(64)} as const);
describe("R2 Workstream D machinery",()=>{
 it("enumerates every preregistered cell and repeat, without count semantics",()=>expect(enumerateCells(matrix,5)).toHaveLength(10));
 it("rejects duplicate or incomplete collections",()=>{const xs=[attempt(0,"0".repeat(64)),attempt(0,"1".repeat(64))];expect(detectCells(xs,[{taskId:"t1",loadoutId:"placebo",repeatIndex:0},{taskId:"t1",loadoutId:"placebo",repeatIndex:1}])).toMatchObject({complete:false,duplicates:["t1\u0000placebo\u00000"]});});
 it("counts only valid attempts while retaining a monotonic invalid retry chain",()=>{const bad={...attempt(0,"0".repeat(64)),status:"invalid",invalidReason:"harness-crash",ledgerRecordSha256:null} as const;const good={...attempt(0,"1".repeat(64)),attemptIndex:1};expect(detectCells([bad,good],[{taskId:"t1",loadoutId:"placebo",repeatIndex:0}])).toMatchObject({complete:true,duplicates:[]});expect(()=>detectCells([{...bad,attemptIndex:2},good],[{taskId:"t1",loadoutId:"placebo",repeatIndex:0}])).toThrow(/monotonic/);});
 it("pairs each treatment loadout once with the same-repeat placebo",()=>{const p=attempt(0,"0".repeat(64));const low={...attempt(0,"1".repeat(64)),loadoutId:"heaven-low"};const med={...attempt(0,"2".repeat(64)),loadoutId:"heaven-med"};const packets=blindAssignments([p,low,med],"rubric/v1");expect(packets).toHaveLength(2);for(const packet of packets)validateJudgeAssignment(packet);expect(new Set(packets.flatMap(packet=>[packet.candidateAArtifactSha256,packet.candidateBArtifactSha256]))).toEqual(new Set(["0".repeat(64),"1".repeat(64),"2".repeat(64)]));expect(JSON.stringify(packets)).not.toMatch(/placebo|heaven|loadout|skill/);});
 it("keeps invalid attempts out of receipts",()=>expect(()=>validateAttempt({...attempt(0,"0".repeat(64)),status:"invalid",invalidReason:"harness-crash",ledgerRecordSha256:null})).not.toThrow());
 it("analysis keeps dose categories distinct and has no fabricated correlation",()=>{const r:any={schema:"hh-ledger/v1",recordedAt:"2026-01-01T00:00:00Z",benchmarkId:"b",task:"t1",arm:"placebo",skillsLoaded:[],model:"m",harness:{name:"h",version:"v"},repeatIndex:0,tokens:{system:null,skillStanding:10,skillInvocation:20,perTurn:30},wallClockMs:40,objectiveEndpoint:{kind:"x",pass:true},judgeVerdict:null};const out=analyse([r],{t1:true});expect(out.groups.placebo.standing).toBe(10);expect(out.groups.placebo.invocation).toBe(20);expect(out.groups.placebo.wholeSession).toBe(30);expect(out.groups.placebo.wallClockMs).toBe(40);expect(out.correlation.n).toBe(0);expect(out.entropyCurve).toHaveLength(6);});
 it("computes paired deltas for every treatment loadout in a task repeat",()=>{const p:any={schema:"hh-ledger/v1",recordedAt:"2026-01-01T00:00:00Z",benchmarkId:"b",task:"t1",arm:"placebo",skillsLoaded:[],model:"m",harness:{name:"h",version:"v"},repeatIndex:0,tokens:{system:null,skillStanding:null,skillInvocation:null,perTurn:null},wallClockMs:0,objectiveEndpoint:{kind:"x",pass:true},judgeVerdict:null};const skill={id:"s",contentSha256:"a".repeat(64)};const low={...p,arm:"heaven",skillsLoaded:[skill],rung:"low",objectiveEndpoint:{kind:"x",pass:false}};const med={...p,arm:"heaven",skillsLoaded:[skill],rung:"med",objectiveEndpoint:{kind:"x",pass:true}};const out=analyse([p,low,med]);expect(out.pairedDeltas.low).toMatchObject({n:1,mean:-1});expect(out.pairedDeltas.med).toMatchObject({n:1,mean:0});});
 it("blocks unreceipted result claims and retired seed terminology",()=>{expect(()=>validateClaims("the result proves 99",0)).toThrow();expect(()=>validateClaims("seed=1",1)).toThrow();expect(()=>validateClaims("repeat 2026 used seed set history",0)).not.toThrow();expect(()=>validateClaims("there are 20 tasks",0)).not.toThrow();});
});
