/**
 * lib/craft/bridges.ts
 *
 * Loader for data/craft/bridges.json — the build-time reachability artifact
 * generated by scripts/craft/derive-reachability.ts (called at the end of
 * every sync-skill-tree.ts run).
 *
 * Two reachability metrics are reported (see derive-reachability.ts header):
 *   Metric A (internal): 100% on ygg2 — all registry fusions reachable from basics.
 *   Metric B (game seeds): 0% on ygg2 — game seeds not in registry ids.
 *
 * Usage in fuse route (priority order):
 *   1. canonical (recipe)   — data/craft/recipes.json (from combinations.md)
 *   2. canonical (derived)  — bridges.json reachableEdges: this layer
 *   3. canonical (starter)  — starter-recipes.ts: flavor overlay for known combos
 *   4. easteregg            — hand-authored surprise combos
 *   5. emergent             — Workers AI
 */

import bridgesRaw from '../../data/craft/bridges.json';

// ---------------------------------------------------------------------------
// Types — mirror the BridgesOutput shape from derive-reachability.ts
// ---------------------------------------------------------------------------

export interface ReachabilityReport {
  totalRegistrySkills: number;
  reachableCount: number;
  /** Internal connectivity % (Metric A: seeds = basic nodes). */
  internalConnectivityPct: number;
  unreachableCount: number;
  /** Game-seed reachable count (Metric B: seeds = only 4 UI primitives). */
  gameSeedReachableCount: number;
  /** Game-seed reachability % (Metric B). On ygg2: 0. */
  gameSeedReachablePct: number;
  /** Back-compat alias for internalConnectivityPct. */
  reachablePct: number;
  gameSeedSlugs: string[];
  seedSlugs: string[];
  generatedAt: string;
}

export interface ReachableEdge {
  result: string;
  prereqs: string[];
}

export interface BridgesData {
  report: ReachabilityReport;
  reachable: string[];
  reachableEdges: ReachableEdge[];
  unreachable: string[];
  /** Registry skill ids reachable from game seeds only (Metric B). On ygg2: []. */
  gameSeedReachable: string[];
}

// ---------------------------------------------------------------------------
// Module-level typed data
// ---------------------------------------------------------------------------

const bridges = bridgesRaw as unknown as BridgesData;

// ---------------------------------------------------------------------------
// Lazy-built lookup map: result skill id → prereqs
// ---------------------------------------------------------------------------

let _edgeMap: Map<string, string[]> | null = null;

function getEdgeMap(): Map<string, string[]> {
  if (_edgeMap) return _edgeMap;
  _edgeMap = new Map<string, string[]>();
  for (const edge of bridges.reachableEdges) {
    if (!_edgeMap.has(edge.result)) {
      _edgeMap.set(edge.result, edge.prereqs);
    }
  }
  return _edgeMap;
}

// ---------------------------------------------------------------------------
// Reachable set (fast O(1) membership test, Metric A)
// ---------------------------------------------------------------------------

let _reachableSet: Set<string> | null = null;

function getReachableSet(): Set<string> {
  if (_reachableSet) return _reachableSet;
  _reachableSet = new Set(bridges.reachable);
  return _reachableSet;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns true if the given skill id is reachable from basic-node roots (Metric A).
 */
export function isReachable(id: string): boolean {
  return getReachableSet().has(id);
}

/**
 * Returns the prereq ids that unlock the given skill via fusion, or undefined.
 */
export function getReachingPrereqs(id: string): string[] | undefined {
  return getEdgeMap().get(id);
}

/**
 * Returns the full reachability report from bridges.json (both metrics).
 */
export function getReachabilityReport(): ReachabilityReport {
  return bridges.report;
}

/**
 * Returns skills not reachable even from basic-node roots (Metric A gap).
 * On ygg2: empty array.
 */
export function getUnreachableSkills(): string[] {
  return bridges.unreachable;
}

/**
 * Returns all reachable edges (result → prereqs) from bridges.json.
 */
export function getAllReachableEdges(): ReachableEdge[] {
  return bridges.reachableEdges;
}

// ---------------------------------------------------------------------------
// 2-input derived recipe lookup (for the fuse route)
// ---------------------------------------------------------------------------

let _derivedPairMap: Map<string, string> | null = null;

/**
 * Returns the result skill id if the two given skill ids (bare slugs, no slash)
 * form an exact 2-prereq fusion in the derived reachable edge list.
 * Returns undefined if no such derived fusion exists.
 *
 * Order-independent.
 *
 * @example
 * findDerivedRecipe('evaluate-output', 'score-relevance') // => 'agent-eval'
 * findDerivedRecipe('api-call', 'tool-use')               // => 'cloud-platform-management'
 */
export function findDerivedRecipe(a: string, b: string): string | undefined {
  if (!_derivedPairMap) {
    _derivedPairMap = new Map<string, string>();
    for (const edge of bridges.reachableEdges) {
      if (edge.prereqs.length === 2) {
        const key = [edge.prereqs[0], edge.prereqs[1]].sort().join('+');
        if (!_derivedPairMap.has(key)) {
          _derivedPairMap.set(key, edge.result);
        }
      }
    }
  }
  const key = [a.toLowerCase().trim(), b.toLowerCase().trim()].sort().join('+');
  return _derivedPairMap.get(key);
}
