/**
 * lib/craft/bridges.ts
 *
 * Loader for data/craft/bridges.json — the build-time reachability artifact
 * generated by scripts/craft/derive-reachability.ts (called at the end of
 * every sync-skill-tree.ts run).
 *
 * Two reachability metrics are reported (see derive-reachability.ts header):
 *   Metric A (internal): 100% on ygg2 — all registry fusions reachable from basics.
 *   Metric B (game seeds + A′ bridges): 65.8% on ygg2 — 160/243 registry skills
 *     reachable from the 4 game seeds via synthetic seed-bridge edges.
 *
 * A′ bridge model (Issue #86 DoD):
 *   84 named-backed fusions reachable (primary DoD metric: 153 named skills).
 *   89 total deterministic fusions = 84 named-backed + 5 unavoidable intermediates.
 *   71 synthetic bridge edges connect game seeds to root basics.
 *   41 purely-generic fusions stay unbridged → emergent/#87 boundary.
 *
 * Usage in fuse route (priority order):
 *   1. canonical (recipe)         — data/craft/recipes.json (from combinations.md)
 *   2. canonical (derived)        — bridges.json reachableEdges (Metric A closures)
 *      2b. seed-bridge resolution — (seed, rootBasic) pair → derived canonical
 *   3. canonical (starter)        — starter-recipes.ts: flavor overlay for known combos
 *   4. easteregg                  — hand-authored surprise combos
 *   5. emergent                   — Workers AI
 */

import bridgesRaw from '../../data/craft/bridges.json';

// ---------------------------------------------------------------------------
// Types — mirror the BridgesOutput shape from derive-reachability.ts
// ---------------------------------------------------------------------------

export interface ReachabilityReport {
  totalRegistrySkills: number;
  reachableCount: number;
  /** Internal connectivity % (Metric A: seeds = basic nodes). */
  internalConnectivityPct: number;
  unreachableCount: number;
  /** Game-seed reachable count (Metric B: seeds = 4 UI primitives + A′ bridges). */
  gameSeedReachableCount: number;
  /** Game-seed reachability % (Metric B). With A′ bridges: ~65.8% on ygg2. */
  gameSeedReachablePct: number;
  /** Back-compat alias for internalConnectivityPct. */
  reachablePct: number;
  /** Named-backed fusion count (primary DoD metric denominator). Target: 84. */
  namedBackedFusionCount: number;
  /**
   * Total deterministic fusion reach = namedBackedFusionCount + unavoidable
   * generic intermediates. Target: 89 (84 + 5). Reviewer transparency field.
   */
  deterministicFusionReachCount: number;
  /**
   * Purely-generic fusions that are unavoidable intermediates on the path to
   * named targets. Exactly 5 on ygg2. Named explicitly for reviewer transparency.
   */
  genericIntermediateFusions: string[];
  /**
   * Distinct named skills (slugs) backing the 84 named-backed fusions.
   * Primary DoD metric. Target: 153.
   */
  reachableNamedSkillCount: number;
  gameSeedSlugs: string[];
  seedSlugs: string[];
  generatedAt: string;
}

export interface ReachableEdge {
  result: string;
  prereqs: string[];
}

/**
 * A synthetic bridge edge connecting a game seed to a root basic skill.
 * Emitted by synthesizeSeedBridges in derive-reachability.ts.
 * `via: 'seed-bridge'` distinguishes synthetic edges from registry edges.
 */
export interface SeedBridgeEdge {
  /** The root basic skill id this bridge makes reachable from the seed. */
  result: string;
  /** Single-element array: the game seed slug that unlocks this basic. */
  prereqs: string[];
  via: 'seed-bridge';
}

export interface BridgesData {
  report: ReachabilityReport;
  reachable: string[];
  reachableEdges: ReachableEdge[];
  unreachable: string[];
  /** Registry skill ids reachable from game seeds + A′ bridges (Metric B). */
  gameSeedReachable: string[];
  /**
   * Synthetic bridge edges: one per root basic in the named-backed target closure.
   * 71 edges on ygg2 staging.
   */
  seedBridges: SeedBridgeEdge[];
  /**
   * Fusion ids (only) reachable from game seeds via A′ bridges — the 89 =
   * 84 named-backed + 5 unavoidable generic intermediates. Distinct from
   * gameSeedReachable (160), which also includes the 71 root basics.
   */
  namedBackedFusions: string[];
}

// ---------------------------------------------------------------------------
// Module-level typed data
// ---------------------------------------------------------------------------

const bridges = bridgesRaw as unknown as BridgesData;

// ---------------------------------------------------------------------------
// Lazy-built lookup map: result skill id → prereqs (Metric A edges)
// ---------------------------------------------------------------------------

let _edgeMap: Map<string, string[]> | null = null;

function getEdgeMap(): Map<string, string[]> {
  if (_edgeMap) return _edgeMap;
  _edgeMap = new Map<string, string[]>();
  for (const edge of bridges.reachableEdges) {
    if (!_edgeMap.has(edge.result)) {
      _edgeMap.set(edge.result, edge.prereqs);
    }
  }
  return _edgeMap;
}

// ---------------------------------------------------------------------------
// Reachable set (fast O(1) membership test, Metric A)
// ---------------------------------------------------------------------------

let _reachableSet: Set<string> | null = null;

function getReachableSet(): Set<string> {
  if (_reachableSet) return _reachableSet;
  _reachableSet = new Set(bridges.reachable);
  return _reachableSet;
}

// ---------------------------------------------------------------------------
// Seed-bridge map: basicId → seedSlug  (for seed-bridge resolution in fuse route)
// ---------------------------------------------------------------------------

let _seedBridgeMap: Map<string, string> | null = null;

function getSeedBridgeMap(): Map<string, string> {
  if (_seedBridgeMap) return _seedBridgeMap;
  _seedBridgeMap = new Map<string, string>();
  for (const edge of bridges.seedBridges) {
    // prereqs is always [seedSlug] for a seed bridge
    if (edge.prereqs.length === 1) {
      _seedBridgeMap.set(edge.result, edge.prereqs[0]);
    }
  }
  return _seedBridgeMap;
}

// ---------------------------------------------------------------------------
// Derived pair map: 'a+b' sorted → result id (Metric A + seed-bridge)
// ---------------------------------------------------------------------------

let _derivedPairMap: Map<string, string> | null = null;

function getDerivedPairMap(): Map<string, string> {
  if (_derivedPairMap) return _derivedPairMap;
  _derivedPairMap = new Map<string, string>();

  // Registry-derived edges (Metric A, exact 2-prereq fusions)
  for (const edge of bridges.reachableEdges) {
    if (edge.prereqs.length === 2) {
      const key = [edge.prereqs[0], edge.prereqs[1]].sort().join('+');
      if (!_derivedPairMap.has(key)) {
        _derivedPairMap.set(key, edge.result);
      }
    }
  }

  // Seed-bridge pairs: (seed, rootBasic) → rootBasic
  // Resolving a seed+basic pair via a seed-bridge makes the basic reachable,
  // which is its own result (the bridge result IS the basic skill id).
  for (const edge of bridges.seedBridges) {
    if (edge.prereqs.length === 1) {
      const seed = edge.prereqs[0];
      const basic = edge.result;
      const key = [seed, basic].sort().join('+');
      if (!_derivedPairMap.has(key)) {
        _derivedPairMap.set(key, basic);
      }
    }
  }

  return _derivedPairMap;
}

// ---------------------------------------------------------------------------
// Named-backed fusion set (fast O(1) membership test) — the 89 fusion-only reach
// (84 named-backed + 5 unavoidable generic intermediates), NOT the 160 that also
// includes root basics.
// ---------------------------------------------------------------------------

let _namedBackedSet: Set<string> | null = null;

function getNamedBackedSet(): Set<string> {
  if (_namedBackedSet) return _namedBackedSet;
  // bridges.namedBackedFusions is the explicit fusion-only Metric B reach set
  // emitted by derive-reachability.ts (gameSeedReachable ∩ fusions).
  _namedBackedSet = new Set(bridges.namedBackedFusions);
  return _namedBackedSet;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns true if the given skill id is reachable from basic-node roots (Metric A).
 */
export function isReachable(id: string): boolean {
  return getReachableSet().has(id);
}

/**
 * Returns the prereq ids that unlock the given skill via fusion, or undefined.
 */
export function getReachingPrereqs(id: string): string[] | undefined {
  return getEdgeMap().get(id);
}

/**
 * Returns the full reachability report from bridges.json (both metrics + A′ fields).
 */
export function getReachabilityReport(): ReachabilityReport {
  return bridges.report;
}

/**
 * Returns skills not reachable even from basic-node roots (Metric A gap).
 * On ygg2: empty array.
 */
export function getUnreachableSkills(): string[] {
  return bridges.unreachable;
}

/**
 * Returns all reachable edges (result → prereqs) from bridges.json.
 */
export function getAllReachableEdges(): ReachableEdge[] {
  return bridges.reachableEdges;
}

/**
 * Returns all synthetic seed-bridge edges from bridges.json.
 * 71 edges on ygg2 staging (one per root basic in the named-backed target closure).
 */
export function getAllSeedBridges(): SeedBridgeEdge[] {
  return bridges.seedBridges;
}

/**
 * Returns the game seed slug that unlocks the given root basic via a seed bridge,
 * or undefined if no seed bridge exists for this basic.
 *
 * Used by the fuse route to resolve (seed, rootBasic) pairs.
 *
 * @example
 * getSeedBridge('web-search')  // => 'web'
 * getSeedBridge('chain-of-thought')  // => 'prompt' (or whatever was assigned)
 */
export function getSeedBridge(basicId: string): string | undefined {
  return getSeedBridgeMap().get(basicId);
}

/**
 * Returns the list of skill ids reachable from game seeds via A′ bridges (Metric B).
 * 160 skills on ygg2 staging.
 */
export function getGameSeedReachable(): string[] {
  return bridges.gameSeedReachable;
}

/**
 * Returns the count of distinct named skills backing the 84 named-backed fusions.
 * Primary DoD metric. Target: 153.
 */
export function getReachableNamedSkillCount(): number {
  return bridges.report.reachableNamedSkillCount;
}

/**
 * Returns the sorted list of named-backed fusion ids (those reachable via game seeds).
 * These are the 84 named-backed fusions + 5 unavoidable generic intermediates.
 */
export function getNamedBackedTargets(): string[] {
  return [...getNamedBackedSet()].sort();
}

// ---------------------------------------------------------------------------
// 2-input derived recipe lookup (for the fuse route)
// ---------------------------------------------------------------------------

/**
 * Returns the result skill id if the two given skill ids (bare slugs, no slash)
 * form an exact 2-prereq fusion in the derived reachable edge list, OR if one
 * of the pair is a game seed and the other is a root basic with a seed bridge.
 *
 * Returns undefined if no such derived fusion exists.
 *
 * Order-independent. O(1).
 *
 * Covers two cases:
 *   1. Registry-derived: (basicA, basicB) → fusionResult  (Metric A edge)
 *   2. Seed-bridge:      (seedSlug, rootBasic) → rootBasic  (Metric B entry point)
 *
 * @example
 * findDerivedRecipe('evaluate-output', 'score-relevance') // => 'agent-eval'
 * findDerivedRecipe('api-call', 'tool-use')               // => 'cloud-platform-management'
 * findDerivedRecipe('web', 'web-search')                  // => 'web-search' (seed bridge)
 */
export function findDerivedRecipe(a: string, b: string): string | undefined {
  const key = [a.toLowerCase().trim(), b.toLowerCase().trim()].sort().join('+');
  return getDerivedPairMap().get(key);
}
