/**
 * lib/craft/contributors.ts
 *
 * Typed, pure accessor over data/craft/contributors.json — the tiny roster of
 * every real Gaia Skill Tree contributor and how many NAMED skills they authored.
 *
 * This is the data behind the "Builders" collection (Lab 002's contributor
 * Pokédex): unlock a canonical skill from a real builder for the first time and
 * you COLLECT that builder. Recognising names like @garrytan, @mattpocock,
 * @karpathy, @addy-osmani, @ruvnet, @obra, @huggingface, @anthropic is the delight.
 *
 * Generated by scripts/craft/sync-skill-tree.ts from gaia-skill-tree/registry/
 * named-skills.json (READ-ONLY upstream). Access is centralised here so UI and
 * tests never reach into the JSON shape directly.
 *
 * Anti-bloat note: the on-disk file stores handles + counts ONLY (no titles, no
 * URLs). The skill-tree profile URL is DERIVED on the fly by this module.
 */

import contributorsData from '../../data/craft/contributors.json';

// ---------------------------------------------------------------------------
// On-disk shape — kept internal to this module.
// ---------------------------------------------------------------------------

interface RawRoster {
  /** Number of distinct contributor handles. */
  total?: number;
  /** handle -> { count } where count = named-skill authorship count. */
  contributors?: Record<string, { count?: number }>;
}

const RAW = contributorsData as RawRoster;

// ---------------------------------------------------------------------------
// Public types.
// ---------------------------------------------------------------------------

/** A resolved contributor roster with readable field names. */
export interface ContributorRoster {
  /** Number of distinct contributor handles with at least one named skill. */
  total: number;
  /** handle -> { count } where count = how many named skills they authored. */
  contributors: Record<string, { count: number }>;
}

/** A single contributor entry, denormalised for list rendering. */
export interface Contributor {
  /** The contributor handle, e.g. "garrytan". */
  handle: string;
  /** How many named skills this contributor authored in the registry. */
  count: number;
}

// ---------------------------------------------------------------------------
// Internal normalisation (defensive — tolerate a partially-written file).
// ---------------------------------------------------------------------------

const NORMALISED: ContributorRoster = (() => {
  const contributors: Record<string, { count: number }> = {};
  const src = RAW.contributors ?? {};
  for (const handle of Object.keys(src)) {
    const raw = src[handle]?.count;
    const count = typeof raw === 'number' && Number.isFinite(raw) && raw > 0 ? raw : 0;
    if (count > 0) contributors[handle] = { count };
  }
  const total =
    typeof RAW.total === 'number' && Number.isFinite(RAW.total)
      ? RAW.total
      : Object.keys(contributors).length;
  return { total, contributors };
})();

// ---------------------------------------------------------------------------
// Public API — pure, no side effects.
// ---------------------------------------------------------------------------

/**
 * Return the full contributor roster (total + handle→count map). The returned
 * object is a fresh copy each call, so callers can mutate freely without
 * poisoning the module cache.
 *
 * @example
 * loadContributors()
 * // => { total: 37, contributors: { garrytan: { count: 47 }, ruvnet: { count: 48 }, … } }
 */
export function loadContributors(): ContributorRoster {
  const contributors: Record<string, { count: number }> = {};
  for (const handle of Object.keys(NORMALISED.contributors)) {
    contributors[handle] = { count: NORMALISED.contributors[handle].count };
  }
  return { total: NORMALISED.total, contributors };
}

/**
 * Return every contributor as a flat list, sorted by named-skill count
 * DESCENDING (ties broken alphabetically by handle for a stable order). This is
 * the order the Builders gallery renders prolific builders — @ruvnet, @garrytan,
 * @mattpocock — first, so their locked chips tease the biggest names early.
 *
 * @example
 * allContributors()
 * // => [ { handle: 'ruvnet', count: 48 }, { handle: 'garrytan', count: 47 }, … ]
 */
export function allContributors(): Contributor[] {
  return Object.entries(NORMALISED.contributors)
    .map(([handle, { count }]) => ({ handle, count }))
    .sort((a, b) => (b.count - a.count) || a.handle.localeCompare(b.handle));
}

/**
 * Derive the deep-link to a contributor's collection on the Gaia Skill Tree.
 *
 * The explorer path WITHOUT a slug resolves to that builder's whole collection:
 * `https://gaiaskilltree.com/named/#explorer/{handle}`.
 *
 * @param handle  The contributor handle, e.g. "garrytan".
 * @returns       The full profile/collection URL.
 *
 * @example
 * contributorProfileUrl('garrytan')
 * // => 'https://gaiaskilltree.com/named/#explorer/garrytan'
 */
export function contributorProfileUrl(handle: string): string {
  return `https://gaiaskilltree.com/named/#explorer/${handle}`;
}

/**
 * Is this handle a real Gaia Skill Tree contributor in the roster?
 * Guards the Builders-unlock path so only genuine builders can be collected.
 *
 * @param handle  A contributor handle (may be undefined-ish at the call site).
 * @returns       True when the handle exists in the roster with ≥1 named skill.
 *
 * @example
 * isKnownContributor('garrytan')   // => true
 * isKnownContributor('not-a-real') // => false
 */
export function isKnownContributor(handle: string): boolean {
  return (
    typeof handle === 'string' &&
    handle.length > 0 &&
    Object.prototype.hasOwnProperty.call(NORMALISED.contributors, handle)
  );
}
