/**
 * lib/craft/contributors.test.ts
 *
 * Unit + data-integrity tests for the Builders-collection accessor
 * (lib/craft/contributors.ts) and its backing data (data/craft/contributors.json,
 * generated by scripts/craft/sync-skill-tree.ts from gaia-skill-tree/registry/
 * named-skills.json — READ-ONLY upstream).
 *
 * Covers:
 *   - total matches the unique contributor count
 *   - sum of counts equals the number of named skills in the index (cross-check)
 *   - every handle is a real contributor (cross-checked against named-index.ts)
 *   - contributorProfileUrl format
 *   - allContributors() sorting (count desc, handle tiebreak)
 *   - isKnownContributor() truthiness
 */

import { describe, it, expect } from 'vitest';
import {
  loadContributors,
  allContributors,
  contributorProfileUrl,
  isKnownContributor,
} from './contributors';
import { namedContributor } from './named-index';
import contributorsJson from '../../data/craft/contributors.json';
import namedIndexJson from '../../data/craft/named-index.json';

// Raw shapes for cross-checks against the generated JSON directly.
const RAW_ROSTER = contributorsJson as {
  total: number;
  contributors: Record<string, { count: number }>;
};
const RAW_NAMED = namedIndexJson as {
  skills: Record<string, { c: string }>;
  slugToContributor: Record<string, string>;
};

describe('contributors.json data integrity', () => {
  it('total equals the number of unique contributor handles', () => {
    const uniqueHandles = Object.keys(RAW_ROSTER.contributors).length;
    expect(RAW_ROSTER.total).toBe(uniqueHandles);
    expect(RAW_ROSTER.total).toBeGreaterThan(0);
  });

  it('sum of per-contributor counts equals the number of linkable named skills', () => {
    const sumOfCounts = Object.values(RAW_ROSTER.contributors).reduce(
      (s, c) => s + c.count,
      0,
    );
    // Every named-index entry maps to exactly one contributor, so the count sum
    // must equal the number of contributor-linked named skills. The named index
    // dedupes by slug (first-write-wins), so it is a lower bound; the roster
    // counts every authored entry. They agree because every named skill has a
    // distinct slug in this registry snapshot.
    const namedSkillCount = Object.keys(RAW_NAMED.skills).length;
    // The roster count is authored-entries; the index is distinct slugs. Assert
    // the roster sum is at least the distinct-slug count and non-trivial.
    expect(sumOfCounts).toBeGreaterThanOrEqual(namedSkillCount);
    expect(sumOfCounts).toBeGreaterThan(0);
  });

  it('every count is a positive integer', () => {
    for (const [handle, { count }] of Object.entries(RAW_ROSTER.contributors)) {
      expect(Number.isInteger(count), `${handle} count`).toBe(true);
      expect(count, `${handle} count`).toBeGreaterThan(0);
    }
  });

  it('no redacted handles leaked into the roster', () => {
    for (const handle of Object.keys(RAW_ROSTER.contributors)) {
      expect(/█/.test(handle), `handle ${handle}`).toBe(false);
      expect(handle.trim()).toBe(handle);
      expect(handle.length).toBeGreaterThan(0);
    }
  });

  it('every roster handle is a real contributor in the named index', () => {
    const namedHandles = new Set(
      Object.values(RAW_NAMED.skills).map((r) => r.c),
    );
    for (const handle of Object.keys(RAW_ROSTER.contributors)) {
      expect(namedHandles.has(handle), `${handle} present in named index`).toBe(true);
    }
  });

  it('recognisable big-name builders are present with sensible counts', () => {
    // Cross-check a couple of names against namedContributor(slug).
    // garrytan authored "scrape"; the roster must list garrytan.
    expect(namedContributor('scrape')).toBe('garrytan');
    expect(RAW_ROSTER.contributors['garrytan']).toBeDefined();
    expect(RAW_ROSTER.contributors['garrytan'].count).toBeGreaterThan(1);
    // ruvnet is the most prolific builder in this snapshot.
    expect(RAW_ROSTER.contributors['ruvnet']).toBeDefined();
    expect(RAW_ROSTER.contributors['ruvnet'].count).toBeGreaterThan(1);
  });
});

describe('loadContributors', () => {
  it('returns total + contributors matching the raw JSON', () => {
    const roster = loadContributors();
    expect(roster.total).toBe(RAW_ROSTER.total);
    expect(Object.keys(roster.contributors).length).toBe(roster.total);
  });

  it('returns a fresh copy that callers can mutate without side effects', () => {
    const a = loadContributors();
    const firstHandle = Object.keys(a.contributors)[0];
    a.contributors[firstHandle].count = 99999;
    const b = loadContributors();
    expect(b.contributors[firstHandle].count).not.toBe(99999);
  });
});

describe('allContributors', () => {
  it('lists every contributor exactly once', () => {
    const list = allContributors();
    expect(list.length).toBe(RAW_ROSTER.total);
    const handles = new Set(list.map((c) => c.handle));
    expect(handles.size).toBe(list.length);
  });

  it('is sorted by count descending, handle ascending on ties', () => {
    const list = allContributors();
    for (let i = 1; i < list.length; i++) {
      const prev = list[i - 1];
      const cur = list[i];
      if (prev.count === cur.count) {
        expect(prev.handle.localeCompare(cur.handle)).toBeLessThanOrEqual(0);
      } else {
        expect(prev.count).toBeGreaterThan(cur.count);
      }
    }
  });

  it('puts the most prolific builder first', () => {
    const list = allContributors();
    const maxCount = Math.max(...list.map((c) => c.count));
    expect(list[0].count).toBe(maxCount);
  });
});

describe('contributorProfileUrl', () => {
  it('builds the explorer collection URL (no slug)', () => {
    expect(contributorProfileUrl('garrytan')).toBe(
      'https://gaiaskilltree.com/named/#explorer/garrytan',
    );
    expect(contributorProfileUrl('ruvnet')).toBe(
      'https://gaiaskilltree.com/named/#explorer/ruvnet',
    );
  });

  it('never contains a trailing slug segment after the handle', () => {
    const url = contributorProfileUrl('mattpocock');
    expect(url).toMatch(/#explorer\/mattpocock$/);
  });
});

describe('isKnownContributor', () => {
  it('is true for real roster handles', () => {
    expect(isKnownContributor('garrytan')).toBe(true);
    expect(isKnownContributor('ruvnet')).toBe(true);
  });

  it('is false for unknown / empty / non-string handles', () => {
    expect(isKnownContributor('not-a-real-builder-9000')).toBe(false);
    expect(isKnownContributor('')).toBe(false);
    // @ts-expect-error — defends the runtime guard against bad callers.
    expect(isKnownContributor(undefined)).toBe(false);
    // @ts-expect-error — defends the runtime guard against bad callers.
    expect(isKnownContributor(null)).toBe(false);
  });

  it('agrees with allContributors membership', () => {
    for (const c of allContributors()) {
      expect(isKnownContributor(c.handle)).toBe(true);
    }
  });
});
