/**
 * lib/craft/named-index.ts
 *
 * Typed, pure accessor over data/craft/named-index.json — the ground-truth map
 * of every REAL Gaia Skill Tree slug to its registry record (contributor, real
 * title, real description, genericSkillRef, level).
 *
 * Generated by scripts/craft/sync-skill-tree.ts from gaia-skill-tree/registry/
 * named-skills.json (READ-ONLY upstream). This module centralises access so the
 * fuse route and tests never reach into the JSON's short-key shape directly.
 *
 * Anti-bloat note: the on-disk records use short keys (c/t/g/d/lvl) to keep the
 * shipped bundle lean; this accessor expands them into readable field names.
 */

import namedIndex from '../../data/craft/named-index.json';

// ---------------------------------------------------------------------------
// On-disk (short-key) shape — kept internal to this module.
// ---------------------------------------------------------------------------

interface RawRecord {
  /** contributor handle */
  c: string;
  /** real registry title */
  t: string;
  /** genericSkillRef (optional) */
  g?: string;
  /** real registry description */
  d: string;
  /** level badge, e.g. "2★" (optional) */
  lvl?: string;
  /** source registry/marketplace (optional: 'mcp' | 'anthropic' | 'skillsmp' | 'registry') */
  src?: 'mcp' | 'anthropic' | 'skillsmp' | 'registry';
  /** source URL (optional) */
  srcUrl?: string;
}

interface RawIndex {
  generatedAt?: string;
  skills?: Record<string, RawRecord>;
  slugToContributor?: Record<string, string>;
  unlinkedSlugs?: string[];
}

const RAW = namedIndex as RawIndex;
const SKILLS: Record<string, RawRecord> = RAW.skills ?? {};
const SLUG_TO_CONTRIBUTOR: Record<string, string> = RAW.slugToContributor ?? {};

// ---------------------------------------------------------------------------
// Public, readable record shape.
// ---------------------------------------------------------------------------

/**
 * A resolved named-skill record with readable field names. Every value is
 * GROUND TRUTH from the Gaia Skill Tree registry.
 */
export interface NamedSkill {
  /** contributor handle, e.g. "garrytan". */
  contributor: string;
  /** real registry title, e.g. "Gstack Scrape — Structured Web Extraction". */
  title: string;
  /** real registry description (what the skill DOES). */
  description: string;
  /** genericSkillRef, e.g. "web-scrape" (present when the registry provides it). */
  genericSkillRef?: string;
  /** level badge, e.g. "2★" (present when the registry provides it). */
  level?: string;
  /** source registry/marketplace (optional) */
  source?: 'mcp' | 'anthropic' | 'skillsmp' | 'registry';
  /** source URL (optional) */
  sourceUrl?: string;
}

/**
 * Look up the ground-truth record for a named-skill slug.
 *
 * @param slug  A bare slug (no leading slash), e.g. `"scrape"`.
 * @returns     The resolved {@link NamedSkill}, or `undefined` when the slug is
 *              not a real named skill in the registry.
 *
 * @example
 * lookupNamedSkill('scrape')
 * // => { contributor: 'garrytan', title: 'Gstack Scrape — …', description: '…', genericSkillRef: 'web-scrape', level: '2★' }
 * lookupNamedSkill('unicorn-dust') // => undefined
 */
export function lookupNamedSkill(slug: string): NamedSkill | undefined {
  const rec = SKILLS[slug];
  if (!rec) return undefined;
  const out: NamedSkill = {
    contributor: rec.c,
    title: rec.t,
    description: rec.d,
  };
  if (rec.g) out.genericSkillRef = rec.g;
  if (rec.lvl) out.level = rec.lvl;
  if (rec.src) out.source = rec.src;
  if (rec.srcUrl) out.sourceUrl = rec.srcUrl;
  return out;
}

/**
 * Return only the contributor handle for a named-skill slug — the minimal
 * datum the emergent→canonical promotion path needs to derive a deep-link.
 * Falls back to the derived `slugToContributor` projection so it keeps working
 * even if a record somehow lacks the rich fields.
 *
 * @param slug  A bare slug (no leading slash), e.g. `"scrape"`.
 * @returns     The contributor handle, or `undefined` when the slug is unknown.
 */
export function namedContributor(slug: string): string | undefined {
  return SKILLS[slug]?.c ?? SLUG_TO_CONTRIBUTOR[slug];
}

/**
 * Return an array of all named skill slugs present in the ground-truth index.
 */
export function getAllNamedSkillSlugs(): string[] {
  return Object.keys(SKILLS);
}

