/**
 * lib/craft/recipes.ts
 *
 * Recipe lookup utilities for Infinite Skill Craft.
 *
 * Data source: data/craft/recipes.json (generated by scripts/craft/sync-skill-tree.ts)
 * Type contract: lib/craft/types.ts (frozen — do not re-define Recipe here)
 */

import recipesData from '../../data/craft/recipes.json';
import { pairKey } from './types';
import type { Recipe } from './types';

// ---------------------------------------------------------------------------
// Types for internal use
// ---------------------------------------------------------------------------

/** Multi-prereq entry stored in recipes.json (not a direct 2-input fusion) */
interface MultiPrereqEntry {
  pairKey: '';
  result: string;
  emoji: string;
  blurb: string;
  prereqs: string[];
  contributor?: string;
  slug?: string;
}

type RecipeEntry = Recipe | MultiPrereqEntry;

// ---------------------------------------------------------------------------
// Load & index
// ---------------------------------------------------------------------------

let _recipeMap: Map<string, Recipe> | null = null;

/**
 * Returns all canonical 2-input recipes from data/craft/recipes.json,
 * typed as `Recipe[]`.  Multi-prereq entries (pairKey === '') are excluded.
 */
export function loadRecipes(): Recipe[] {
  return (recipesData as RecipeEntry[]).filter(
    (r): r is Recipe => r.pairKey !== ''
  );
}

/**
 * Returns the pre-built pairKey → Recipe lookup map (memoised singleton).
 * Initialised on first call.
 */
function getRecipeMap(): Map<string, Recipe> {
  if (_recipeMap) return _recipeMap;
  _recipeMap = new Map<string, Recipe>();
  for (const recipe of loadRecipes()) {
    _recipeMap.set(recipe.pairKey, recipe);
  }
  return _recipeMap;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up a canonical recipe for a given pair of skill slugs.
 *
 * Order-independent — delegates key normalisation to `pairKey(a, b)`.
 *
 * @param a  Slug of the first skill (e.g. `"api-call"`)
 * @param b  Slug of the second skill (e.g. `"tool-use"`)
 * @returns  The matching `Recipe`, or `undefined` if no canonical recipe exists.
 *
 * @example
 * findRecipe('api-call', 'tool-use')
 * // => { pairKey: 'api-call+tool-use', result: 'flow-nexus-platform', ... }
 */
export function findRecipe(a: string, b: string): Recipe | undefined {
  return getRecipeMap().get(pairKey(a, b));
}

/**
 * Returns the deep-link URL to the skill page on gaiaskilltree.com for a
 * named/contributor skill.
 *
 * Format: `https://gaiaskilltree.com/named/#explorer/{contributor}/{slug}`
 *
 * @param contributor  The contributor handle (e.g. `"ruvnet"`).
 * @param slug         The skill slug under that contributor (e.g. `"swarm-advanced"`).
 * @returns            The full URL string, or `undefined` if either argument is absent.
 *
 * @example
 * skillTreeUrl('ruvnet', 'swarm-advanced')
 * // => 'https://gaiaskilltree.com/named/#explorer/ruvnet/swarm-advanced'
 *
 * skillTreeUrl(undefined, 'generic-skill')
 * // => undefined
 */
export function skillTreeUrl(
  contributor: string | undefined,
  slug: string | undefined
): string | undefined {
  if (!contributor || !slug) return undefined;
  return `https://gaiaskilltree.com/named/#explorer/${contributor}/${slug}`;
}
